version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: ./django_backend/Dockerfile
      args:
       - DEV=true
    ports:
      - "8030:8030"
    volumes:
      - ./django_backend:/django_backend
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8030"
