version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: ./django_backend/Dockerfile
      args:
       - DEV=true
    ports:
      - "8030:8030"
    volumes:
      - ./django_backend:/django_backend
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8030"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=maris
      - DB_PASS=pass123
    depends_on:
      - db

  db:
    image: postgres:16-alpine3.18
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=maris
      - POSTGRES_PASSWORD=pass123

volumes:
  dev-db-data: